### ISSUE TITLE
Traffic Light Detection

### ISSUE THREAD

**Issue by clockworkbits** [clockworkbits/CarND-Capstone#3]
Detection: Detect the traffic light and its color from the `/image_color`. The topic `/vehicle/traffic_lights` contains the exact location and status of all traffic lights in simulator, so you can test your output.
Waypoint publishing: Once you have correctly identified the traffic light and determined its position, you can convert it to a waypoint index and publish it.

**Comment by jodiealaine** [comment]
This issue was split into the following issues and all have now been completed:

- #6 [TLD] Report next red light without actual detection
- #7 [TLD] Build DNN model for traffic light detection
- #8 [TLD] Train DNN for traffic light detection 
- #9  [TLD] Load Traffic Light Detection DNN into ros, and run inference
